stages:
  - build
  - cov
  - fossid

build:
  stage: build
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x tl_rf4ce_zrc2_sdk/*.sh
    - date
    - ls ./tl_rf4ce_zrc2_sdk/
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS1  -import ./tl_rf4ce_zrc2_sdk/ -cleanBuild tl_rf4ce_zrc2_sdk/zrc2_rc_8258
    - date

  artifacts:
    paths:
    - "tl_rf4ce_zrc2_sdk/zrc2_rc_8258/*.bin"
    - "tl_rf4ce_zrc2_sdk/zrc2_rc_8258/*.lst"
    - "tl_rf4ce_zrc2_sdk/zrc2_rc_8258/*.elf"
    
# The cov job definition
cov:
  variables:    
    CODE_COMPILE_ARCH: 'TC32'    
    COV_PF_CATALOG: 'ZIGBEE'  
  stage: cov 
  tags:    
    - COV    
    - LINUX    
    - TC32
  before_script:  
  script:    
    - chmod +x tl_zigbee_sdk/tools/*.sh    
    - $COV_B COV_$CI_PROJECT_NAME $COV_B_TEMPLATE/$CODE_COMPILE_ARCH $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./tl_rf4ce_zrc2_sdk/  -cleanBuild tl_rf4ce_zrc2_sdk/zrc2_rc_8258    
    - $COV_A COV_$CI_PROJECT_NAME    
    - cov_add_commit_steam_project_2_platform.sh
        
fossid:
  tags:
    - FOSSID
  stage: fossid
  script:
    - fossid_check.sh
  artifacts:
    paths:
    - fossid*.txt
  #when: manual

