stages:
  - scc
  - genLicense
  - checkLicense
  - build_tc32
  - cov
  - fossid
  - plainPW_check
  - misspellChecking

scc:
  stage: scc
  script:
    - echo "Enter scc stage"
    - scc | tee scc.txt
    - bash /usr/bin/scc_calc.sh
    - echo  "The End SCC result:"
    - cat scc.txt
  artifacts:
    paths:
    - scc.txt
build_tc32:
  stage: build_tc32
  tags:
    - LINUX
    - TC32
  before_script:
  script:
    - which tc32-elf-gcc
    - chmod +x tl_rf4ce_zrc2_sdk/*.sh
    - date
    - ls ./tl_rf4ce_zrc2_sdk/
    - $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS1  -import ./tl_rf4ce_zrc2_sdk/ -cleanBuild tl_rf4ce_zrc2_sdk/zrc2_rc_8258
    - date

  artifacts:
    paths:
    - "tl_rf4ce_zrc2_sdk/zrc2_rc_8258/*.bin"
    - "tl_rf4ce_zrc2_sdk/zrc2_rc_8258/*.lst"
    - "tl_rf4ce_zrc2_sdk/zrc2_rc_8258/*.elf"
    
# The cov job definition
cov:
  variables:    
    CODE_COMPILE_ARCH: 'TC32'    
    COV_PF_CATALOG: 'ZIGBEE'  
  stage: cov 
  tags:    
    - COV    
    - LINUX    
    - TC32
  before_script:  
  script:    
    - chmod +x tl_rf4ce_zrc2_sdk/*.sh  
    - $COV_B COV_$CI_PROJECT_NAME $COV_B_TEMPLATE/$CODE_COMPILE_ARCH $TC32_ECLIPSE_BUILD  -data ${CI_PIPELINE_ID}_WS  -import ./tl_rf4ce_zrc2_sdk/  -cleanBuild tl_rf4ce_zrc2_sdk/zrc2_rc_8258    
    - $COV_A COV_$CI_PROJECT_NAME    
    - cov_add_commit_steam_project_2_platform.sh
        
fossid:
  tags:
    - FOSSID
  stage: fossid
  script:
    - fossid_check.sh
  artifacts:
    paths:
    - fossid*.txt
  when: manual

plainPW_check:
  stage: plainPW_check 
  script:
    - echo "Enter Plain Password checking stage"
    - check_plain_weak_password | tee result.txt
    - ls -l result.txt
    - echo "Error List:"
    - cat result.txt
  artifacts:
    paths:
    - result.txt
  when: manual

misspellChecking:
  stage: misspellChecking
  tags:
    - LINUX
  script:
    - echo "--------------- Begin ------------------------"
    - misspell-check
    - echo "---------------- End -----------------------"
  artifacts:
    paths:
    - misspell_result.txt
